"#ifndef _BLOOM_STRUCTURES_FXH_\n"
"#define _BLOOM_STRUCTURES_FXH_\n"
"\n"
"#ifndef __cplusplus\n"
"#   include \"ShaderDefinitions.fxh\"\n"
"#elif !defined(_SHADER_DEFINITIONS_FXH_)\n"
"#   error \"Include ShaderDefinitions.fxh before including this file\"\n"
"#endif\n"
"\n"
"// Implemented based on this article\n"
"// https://www.froyok.fr/blog/2021-12-ue4-custom-bloom/\n"
"struct BloomAttribs\n"
"{\n"
"    // The intensity of the bloom effect.\n"
"    float Intensity      DEFAULT_VALUE(0.15f);\n"
"\n"
"    // This value determines the minimum brightness required for a pixel to contribute to the bloom effect.\n"
"    float Threshold      DEFAULT_VALUE(1.0);\n"
"\n"
"    // This value determines the softness of the threshold. A higher value will result in a softer threshold.\n"
"    float SoftTreshold  DEFAULT_VALUE(0.125);\n"
"\n"
"    // This variable controls the size of the bloom effect. A larger radius will result in a larger area of the image being affected by the bloom effect.\n"
"    float Radius         DEFAULT_VALUE(0.75);\n"
"};\n"
"#ifdef CHECK_STRUCT_ALIGNMENT\n"
"    CHECK_STRUCT_ALIGNMENT(BloomAttribs);\n"
"#endif\n"
"\n"
"#endif //_BLOOM_STRUCTURES_FXH_\n"
