"#include \"FullScreenTriangleVSOutput.fxh\"\n"
"#include \"BloomStructures.fxh\"\n"
"\n"
"cbuffer cbBloomAttribs\n"
"{\n"
"    BloomAttribs g_BloomAttribs;\n"
"}\n"
"\n"
"Texture2D<float3> g_TextureInput;\n"
"SamplerState      g_TextureInput_sampler;\n"
"\n"
"Texture2D<float3> g_TextureDownsampled;\n"
"SamplerState      g_TextureDownsampled_sampler;\n"
"\n"
"float3 SampleColor(float2 Texcoord, float2 Offset)\n"
"{\n"
"    return g_TextureDownsampled.SampleLevel(g_TextureDownsampled_sampler, Texcoord + Offset, 0.0);\n"
"}\n"
"\n"
"float3 ComputeUpsampledTexturePS(in FullScreenTriangleVSOutput VSOut) : SV_Target0\n"
"{\n"
"    float2 TextureResolution;\n"
"    g_TextureInput.GetDimensions(TextureResolution.x, TextureResolution.y);\n"
"\n"
"    float2 TexelSize = rcp(TextureResolution);\n"
"    float2 CenterTexcoord = NormalizedDeviceXYToTexUV(VSOut.f2NormalizedXY);\n"
"\n"
"    float3 A = SampleColor(CenterTexcoord, TexelSize * float2(-1.0, +1.0));\n"
"    float3 B = SampleColor(CenterTexcoord, TexelSize * float2(+0.0, +1.0));\n"
"    float3 C = SampleColor(CenterTexcoord, TexelSize * float2(+1.0, +1.0));\n"
"\n"
"    float3 D = SampleColor(CenterTexcoord, TexelSize * float2(-1.0, +0.0));\n"
"    float3 E = SampleColor(CenterTexcoord, TexelSize * float2(+0.0, +0.0));\n"
"    float3 F = SampleColor(CenterTexcoord, TexelSize * float2(+1.0, +0.0));\n"
"\n"
"    float3 G = SampleColor(CenterTexcoord, TexelSize * float2(-1.0, -1.0));\n"
"    float3 H = SampleColor(CenterTexcoord, TexelSize * float2(+0.0, -1.0));\n"
"    float3 I = SampleColor(CenterTexcoord, TexelSize * float2(+1.0, -1.0));\n"
"\n"
"    float3 ColorSum = E * 0.25;\n"
"    ColorSum += (B + D + F + H) * 0.125;\n"
"    ColorSum += (A + C + G + I) * 0.0625;\n"
"\n"
"    if (VSOut.uInstID != 0u)\n"
"    {\n"
"        float3 SourceColor = g_TextureInput.SampleLevel(g_TextureInput_sampler, CenterTexcoord, 0.0);\n"
"        return SourceColor + g_BloomAttribs.Intensity * ColorSum;\n"
"    }\n"
"    else\n"
"    {\n"
"        float3 SourceColor = g_TextureInput.SampleLevel(g_TextureInput_sampler, CenterTexcoord, 0.0);\n"
"        return SourceColor + ColorSum;\n"
"    }\n"
"}\n"
