"#include \"FullScreenTriangleVSOutput.fxh\"\n"
"\n"
"Texture2D<float3> g_TextureInput;\n"
"SamplerState      g_TextureInput_sampler;\n"
"\n"
"float3 SampleColor(float2 Texcoord, float2 Offset)\n"
"{\n"
"    return g_TextureInput.SampleLevel(g_TextureInput_sampler, Texcoord + Offset, 0.0);\n"
"}\n"
"\n"
"float3 ComputeDownsampledTexturePS(in FullScreenTriangleVSOutput VSOut) : SV_Target0\n"
"{\n"
"    float2 TextureResolution;\n"
"    g_TextureInput.GetDimensions(TextureResolution.x, TextureResolution.y);\n"
"\n"
"    float2 TexelSize = rcp(TextureResolution);\n"
"    float2 CenterTexcoord = NormalizedDeviceXYToTexUV(VSOut.f2NormalizedXY.xy);\n"
"\n"
"    float3 A = SampleColor(CenterTexcoord, TexelSize * float2(-2.0, +2.0));\n"
"    float3 B = SampleColor(CenterTexcoord, TexelSize * float2(+0.0, +2.0));\n"
"    float3 C = SampleColor(CenterTexcoord, TexelSize * float2(+2.0, +2.0));\n"
"\n"
"    float3 D = SampleColor(CenterTexcoord, TexelSize * float2(-2.0, +0.0));\n"
"    float3 E = SampleColor(CenterTexcoord, TexelSize * float2(+0.0, +0.0));\n"
"    float3 F = SampleColor(CenterTexcoord, TexelSize * float2(+2.0, +0.0));\n"
"\n"
"    float3 G = SampleColor(CenterTexcoord, TexelSize * float2(-2.0, -2.0));\n"
"    float3 H = SampleColor(CenterTexcoord, TexelSize * float2(+0.0, -2.0));\n"
"    float3 I = SampleColor(CenterTexcoord, TexelSize * float2(+2.0, -2.0));\n"
"\n"
"    float3 J = SampleColor(CenterTexcoord, TexelSize * float2(-1.0, +1.0));\n"
"    float3 K = SampleColor(CenterTexcoord, TexelSize * float2(+1.0, +1.0));\n"
"    float3 L = SampleColor(CenterTexcoord, TexelSize * float2(-1.0, -1.0));\n"
"    float3 M = SampleColor(CenterTexcoord, TexelSize * float2(+1.0, -1.0));\n"
"\n"
"    float3 OutColor = float3(0.0f, 0.0f, 0.0f);\n"
"    OutColor += (A + C + G + I) * 0.03125;\n"
"    OutColor += (B + D + F + H) * 0.0625;\n"
"    OutColor += (E + J + K + L + M) * 0.125;\n"
"    return OutColor;\n"
"}\n"
