"#ifndef _BOUND_BOX_STRUCTURES_FXH_\n"
"#define _BOUND_BOX_STRUCTURES_FXH_\n"
"\n"
"struct BoundBoxAttribs\n"
"{\n"
"    float4x4 Transform;\n"
"    float4   Color;\n"
"\n"
"    float PatternLength;\n"
"    uint  PatternMask;\n"
"    float Padding0;\n"
"    float Padding1;\n"
"};\n"
"\n"
"struct BoundBoxVSOutput\n"
"{\n"
"    float4 Pos              : SV_Position;\n"
"    float4 ClipPos          : CLIP_POS;\n"
"    float4 PrevClipPos      : PREV_CLIP_POS;\n"
"    float4 EdgeStartClipPos : EDGE_START_CLIP_POS;\n"
"};\n"
"\n"
"#endif // _BOUND_BOX_STRUCTURES_FXH_\n"
