"#ifndef _DEPTH_OF_FIELD_STRUCTURES_FXH_\n"
"#define _DEPTH_OF_FIELD_STRUCTURES_FXH_\n"
"\n"
"#ifndef __cplusplus\n"
"#   include \"ShaderDefinitions.fxh\"\n"
"#elif !defined(_SHADER_DEFINITIONS_FXH_)\n"
"#   error \"Include ShaderDefinitions.fxh before including this file\"\n"
"#endif\n"
"\n"
"#define DOF_KERNEL_SAMPLE_COUNT 22\n"
"\n"
"struct DepthOfFieldAttribs\n"
"{\n"
"    // The intensity of the depth of field effect.\n"
"    float BokehRadius     DEFAULT_VALUE(4.0f);\n"
"\n"
"    // The distance from the camera at which the depth of field effect is focused.\n"
"    float FocusDistance   DEFAULT_VALUE(10.0f);\n"
"\n"
"    // The range of distances from the focus distance at which the depth of field effect is applied.\n"
"    float FocusRange      DEFAULT_VALUE(3.0f);\n"
"\n"
"    float Padding0        DEFAULT_VALUE(0.0f);\n"
"};\n"
"#ifdef CHECK_STRUCT_ALIGNMENT\n"
"    CHECK_STRUCT_ALIGNMENT(DepthOfFieldAttribs);\n"
"#endif\n"
"\n"
"#endif // _DEPTH_OF_FIELD_STRUCTURES_FXH_\n"
