"#include \"FullScreenTriangleVSOutput.fxh\"\n"
"#include \"DepthOfFieldStructures.fxh\"\n"
"\n"
"cbuffer cbDepthOfFieldAttribs\n"
"{\n"
"    DepthOfFieldAttribs g_DOFAttribs;\n"
"}\n"
"\n"
"Texture2D<float3> g_TextureColor;\n"
"Texture2D<float>  g_TextureCoC;\n"
"Texture2D<float4> g_TextureDoF;\n"
"\n"
"SamplerState g_TextureDoF_sampler;\n"
"\n"
"float3 ComputeCombinedTexturePS(in FullScreenTriangleVSOutput VSOut) : SV_Target0\n"
"{\n"
"    float3 Source = g_TextureColor.Load(int3(VSOut.f4PixelPos.xy, 0));\n"
"\n"
"	float  CoC = g_TextureCoC.Load(int3(VSOut.f4PixelPos.xy, 0));\n"
"	float4 DoF = g_TextureDoF.SampleLevel(g_TextureDoF_sampler, NormalizedDeviceXYToTexUV(VSOut.f2NormalizedXY.xy), 0.0);\n"
"\n"
"	float Strength = smoothstep(0.1, 1.0, abs(CoC));\n"
"	return lerp(Source.rgb, DoF.rgb, Strength + DoF.a - Strength * DoF.a);\n"
"}\n"
