"#include \"FullScreenTriangleVSOutput.fxh\"\n"
"#include \"DepthOfFieldStructures.fxh\"\n"
"\n"
"\n"
"Texture2D<float4> g_TextureDoF;\n"
"SamplerState      g_TextureDoF_sampler;\n"
"\n"
"float4 SampleColor(float2 Texcoord, float2 Offset)\n"
"{\n"
"    return g_TextureDoF.SampleLevel(g_TextureDoF_sampler, Texcoord + Offset, 0.0);\n"
"}\n"
"\n"
"float4 ComputePostfilteredTexturePS(in FullScreenTriangleVSOutput VSOut) : SV_Target0\n"
"{\n"
"    float2 TextureResolution;\n"
"    g_TextureDoF.GetDimensions(TextureResolution.x, TextureResolution.y);\n"
"\n"
"    float2 TexelSize = rcp(TextureResolution);\n"
"    float2 CenterTexcoord = NormalizedDeviceXYToTexUV(VSOut.f2NormalizedXY.xy);\n"
"\n"
"    float4 A = SampleColor(CenterTexcoord, TexelSize * float2(-0.5, -0.5));\n"
"    float4 B = SampleColor(CenterTexcoord, TexelSize * float2(-0.5, +0.5));\n"
"    float4 C = SampleColor(CenterTexcoord, TexelSize * float2(+0.5, -0.5));\n"
"    float4 D = SampleColor(CenterTexcoord, TexelSize * float2(+0.5, +0.5));\n"
"\n"
"    return 0.25 * (A + B + C + D);\n"
"}\n"
