"#include \"FullScreenTriangleVSOutput.fxh\"\n"
"#include \"DepthOfFieldStructures.fxh\"\n"
"#include \"BasicStructures.fxh\"\n"
"#include \"PostFX_Common.fxh\"\n"
"\n"
"cbuffer cbCameraAttribs\n"
"{\n"
"    CameraAttribs g_Camera;\n"
"}\n"
"\n"
"cbuffer cbDepthOfFieldAttribs\n"
"{\n"
"    DepthOfFieldAttribs g_DOFAttribs;\n"
"}\n"
"\n"
"Texture2D<float> g_TextureDepth;\n"
"\n"
"float SampleDepth(int2 PixelCoord)\n"
"{\n"
"    return g_TextureDepth.Load(int3(PixelCoord, 0));\n"
"}\n"
"\n"
"float ComputeCircleOfConfusionPS(in FullScreenTriangleVSOutput VSOut) : SV_Target0\n"
"{\n"
"    float LinearDepth = DepthToCameraZ(SampleDepth(int2(VSOut.f4PixelPos.xy)), g_Camera.mProj);\n"
"	float CoC = (LinearDepth - g_DOFAttribs.FocusDistance) / g_DOFAttribs.FocusRange;\n"
"	return clamp(CoC, -1, 1) * g_DOFAttribs.BokehRadius;\n"
"}\n"
