"#include \"BasicStructures.fxh\"\n"
"#include \"ToneMapping.fxh\"\n"
"#include \"ShaderUtilities.fxh\"\n"
"\n"
"cbuffer cbCameraAttribs\n"
"{\n"
"    CameraAttribs g_Camera;\n"
"    CameraAttribs g_PrevCamera;\n"
"}\n"
"\n"
"cbuffer cbEnvMapRenderAttribs\n"
"{\n"
"    ToneMappingAttribs g_ToneMappingAttribs;\n"
"\n"
"    float AverageLogLum;\n"
"    float MipLevel;\n"
"    float Alpha;\n"
"    float Unusued2;\n"
"}\n"
"\n"
"TextureCube  EnvMap;\n"
"SamplerState EnvMap_sampler;\n"
"\n"
"struct SampleEnvMapOutput\n"
"{\n"
"    float4 Color;\n"
"    float2 MotionVector;\n"
"};\n"
"\n"
"SampleEnvMapOutput SampleEnvMap(in float4 ClipPos)\n"
"{\n"
"    float4 WorldPos  = mul(ClipPos, g_Camera.mViewProjInv);\n"
"    float3 Direction = WorldPos.xyz / WorldPos.w - g_Camera.f4Position.xyz;\n"
"    float3 Color     = EnvMap.SampleLevel(EnvMap_sampler, Direction, MipLevel).rgb;\n"
"\n"
"#if TONE_MAPPING_MODE > TONE_MAPPING_MODE_NONE\n"
"    Color.rgb = ToneMap(Color.rgb, g_ToneMappingAttribs, AverageLogLum);\n"
"#endif\n"
"\n"
"#if CONVERT_OUTPUT_TO_SRGB\n"
"    Color.rgb = pow(Color.rgb, float3(1.0 / 2.2, 1.0 / 2.2, 1.0 / 2.2));\n"
"#endif\n"
"\n"
"    float2 MotionVector = float2(0.0, 0.0);\n"
"#if COMPUTE_MOTION_VECTORS\n"
"    float4 PrevClipPos = mul(float4(Direction, 0.0), g_PrevCamera.mViewProj);\n"
"    PrevClipPos.xy /= PrevClipPos.w;\n"
"    MotionVector = GetMotionVector(ClipPos.xy, PrevClipPos.xy, g_Camera.f2Jitter, g_PrevCamera.f2Jitter);\n"
"#endif\n"
"\n"
"    SampleEnvMapOutput Output;\n"
"    Output.Color        = float4(Color.rgb, Alpha);\n"
"    Output.MotionVector = MotionVector;\n"
"    return Output;\n"
"}\n"
"\n"
"#include \"PSMainGenerated.generated\"\n"
"// void main(in  float4 Pos     : SV_Position,\n"
"//           in  float4 ClipPos : CLIP_POS,\n"
"//           out float4 Color   : SV_Target)\n"
"// {\n"
"//     Color = SampleEnvMap(ClipPos).Color;\n"
"// }\n"
