"#ifndef _SCREEN_SPACE_AMBIENT_OCCLUSION_STRUCTURES_FXH_\n"
"#define _SCREEN_SPACE_AMBIENT_OCCLUSION_STRUCTURES_FXH_\n"
"\n"
"#ifndef __cplusplus\n"
"#   include \"ShaderDefinitions.fxh\"\n"
"#elif !defined(_SHADER_DEFINITIONS_FXH_)\n"
"#   error \"Include ShaderDefinitions.fxh before including this file\"\n"
"#endif\n"
"\n"
"// Maximum mip level of depth buffer used in XeGTAO algorithm\n"
"#define SSAO_DEPTH_PREFILTERED_MAX_MIP 4\n"
"\n"
"// Maximum mip level of history buffer used in the resampled history step\n"
"#define SSAO_DEPTH_HISTORY_CONVOLUTED_MAX_MIP 4\n"
"\n"
"// Maximum number of frames using the fixed history buffer\n"
"#define SSAO_OCCLUSION_HISTORY_MAX_FRAMES_WITH_HISTORY_FIX 4\n"
"\n"
"// Maximum number of frames using denoiser\n"
"#define SSAO_OCCLUSION_HISTORY_MAX_FRAMES_WITH_DENOISING 8\n"
"\n"
"// Number of slices used in the calculation of ambient occlusion\n"
"#define SSAO_SLICE_COUNT 3\n"
"\n"
"// Number of samples per slice used in the calculation of ambient occlusion\n"
"#define SSAO_SAMPLES_PER_SLICE 3\n"
"\n"
"// Number of samples on the Poisson disc used in the spatial reconstruction step\n"
"#define SSAO_SPATIAL_RECONSTRUCTION_SAMPLES 8\n"
"\n"
"// Sets the sigma in Gaussian weighting for points on the Poisson disk at the spatial reconstruction step\n"
"#define SSAO_SPATIAL_RECONSTRUCTION_SIGMA 0.9\n"
"\n"
"// Sets the sigma of spatial component in the bilateral upsampling step\n"
"#define SSAO_BILATERAL_UPSAMPLING_SIGMA 0.9\n"
"\n"
"// Sets the sigma of depth component in the bilateral upsampling step\n"
"#define SSAO_BILATERAL_UPSAMPLING_DEPTH_SIGMA 0.0075\n"
"\n"
"// Defines the threshold for pixel velocity difference that determines whether a pixel is considered to have \"no history\" in the temporal accumulation step\n"
"#define SSAO_TEMPORAL_MOTION_VECTOR_DIFF_FACTOR 128.0\n"
"\n"
"// Sets the minimum value for the variance gamma in the temporal accumulation step\n"
"#define SSAO_TEMPORAL_MIN_VARIANCE_GAMMA 0.5\n"
"\n"
"// Sets the maximum value for the variance gamma in the temporal accumulation step\n"
"#define SSAO_TEMPORAL_MAX_VARIANCE_GAMMA 2.5\n"
"\n"
"// Determines the similarity of the depth in the current and previous frame to calculate the disoclusion in the temporal accumulation step\n"
"#define SSAO_DISOCCLUSION_DEPTH_THRESHOLD 0.01\n"
"\n"
"struct ScreenSpaceAmbientOcclusionAttribs\n"
"{\n"
"    // The value defines world space radius of ambient occlusion\n"
"    float EffectRadius                DEFAULT_VALUE(1.0f);\n"
"\n"
"    // Gently reduces sample impact as it gets out of the \'Effect radius\' bounds\n"
"    float EffectFalloffRange          DEFAULT_VALUE(0.615f);\n"
"\n"
"    // Use different value as compared to the ground truth radius to counter inherent screen space biases\n"
"    float RadiusMultiplier            DEFAULT_VALUE(1.457f);\n"
"\n"
"    // Controls the main trade-off between performance (memory bandwidth) and quality (temporal stability is the first affected, thin objects next)\n"
"    float DepthMIPSamplingOffset      DEFAULT_VALUE(3.3f);\n"
"\n"
"    // The value is responsible for interpolating between the current and previous frame\n"
"    float TemporalStabilityFactor     DEFAULT_VALUE(0.9f);\n"
"\n"
"    // Controls the kernel size in the spatial reconstruction step. Increasing the value increases the deviation from the ground truth but reduces the noise\n"
"    float SpatialReconstructionRadius DEFAULT_VALUE(4.0f);\n"
"\n"
"    // If this parameter is set to true, the current frame will be written to the current history buffer without interpolation with the previous history buffer\n"
"    BOOL  ResetAccumulation           DEFAULT_VALUE(FALSE);\n"
"\n"
"    // Padding 1\n"
"    float Padding1                    DEFAULT_VALUE(0);\n"
"};\n"
"\n"
"#ifdef CHECK_STRUCT_ALIGNMENT\n"
"    CHECK_STRUCT_ALIGNMENT(ScreenSpaceAmbientOcclusionAttribs);\n"
"#endif\n"
"\n"
"#endif //_SCREEN_SPACE_AMBIENT_OCCLUSION_STRUCTURES_FXH_\n"
