"#ifndef _SCREEN_SPACE_REFLECTION_STRUCTURES_FXH_\n"
"#define _SCREEN_SPACE_REFLECTION_STRUCTURES_FXH_\n"
"\n"
"#ifndef __cplusplus\n"
"#   include \"ShaderDefinitions.fxh\"\n"
"#elif !defined(_SHADER_DEFINITIONS_FXH_)\n"
"#   error \"Include ShaderDefinitions.fxh before including this file\"\n"
"#endif\n"
"\n"
"// Maximum mip level of depth buffer used in the Hi-Z tracing\n"
"#define SSR_DEPTH_HIERARCHY_MAX_MIP 6\n"
"\n"
"// Number of samples on the Poisson disc used at the stage of spatial reconstruction\n"
"#define SSR_SPATIAL_RECONSTRUCTION_SAMPLES 8\n"
"\n"
"// Parameter regulates from which level of roughness the maximum radius will be used at the stage of spatial reconstruction\n"
"#define SSR_SPATIAL_RECONSTRUCTION_ROUGHNESS_FACTOR 5\n"
"\n"
"// Sets the sigma in Gaussian weighting for points on the Poisson disk at the stage of spatial reconstruction\n"
"#define SSR_SPATIAL_RECONSTRUCTION_SIGMA 0.9\n"
"\n"
"// Determines the similarity threshold of depth between the current and previous frame to calculate disocclusion in the temporal accumulation step.\n"
"#define SSR_DISOCCLUSION_THRESHOLD 0.9\n"
"\n"
"// Sets the value for the variance gamma in the temporal accumulation step\n"
"#define SSR_TEMPORAL_VARIANCE_GAMMA 2.5\n"
"\n"
"// Defines the factor for edge-stopping function on world-space normals in the bilateral filtering step\n"
"#define SSR_BILATERAL_SIGMA_NORMAL 128.0\n"
"\n"
"// Defines the factor for edge-stopping function on linear depth buffer in the bilateral filtering step\n"
"#define SSR_BILATERAL_SIGMA_DEPTH 1.0\n"
"\n"
"// Defines the variance threshold at which the bilateral filtering should be launched\n"
"#define SSR_BILATERAL_VARIANCE_EXIT_THRESHOLD 0.00005\n"
"\n"
"// Defines the variance threshold at which the maximum radius of the bilateral filter is used\n"
"#define SSS_BILATERAL_VARIANCE_ESTIMATE_THRESHOLD 0.001\n"
"\n"
"// Parameter regulates from which level of roughness the maximum radius will be used at the stage of bilateral filtering\n"
"#define SSR_BILATERAL_ROUGHNESS_FACTOR 8\n"
"\n"
"struct ScreenSpaceReflectionAttribs\n"
"{\n"
"    // A bias for accepting hits. Larger values may cause streaks, lower values may cause holes\n"
"    float DepthBufferThickness               DEFAULT_VALUE(0.025f);\n"
"\n"
"    // Regions with a roughness value greater than this threshold won\'t spawn rays\"\n"
"    float RoughnessThreshold                 DEFAULT_VALUE(0.2f);\n"
"\n"
"    // The most detailed MIP map level in the depth hierarchy. Perfect mirrors always use 0 as the most detailed level\n"
"    uint  MostDetailedMip                    DEFAULT_VALUE(0);\n"
"\n"
"    // Padding 0\n"
"    uint  Padding0                           DEFAULT_VALUE(0);\n"
"\n"
"    // A boolean to describe the space used to store roughness in the materialParameters texture.\n"
"    BOOL  IsRoughnessPerceptual              DEFAULT_VALUE(TRUE);\n"
"\n"
"    // The channel to read the roughness from the materialParameters texture\n"
"    uint  RoughnessChannel                   DEFAULT_VALUE(0);\n"
"\n"
"    // Caps the maximum number of lookups that are performed from the depth buffer hierarchy. Most rays should terminate after approximately 20 lookups\n"
"    uint  MaxTraversalIntersections          DEFAULT_VALUE(128);\n"
"\n"
"    // This parameter is aimed at reducing noise by modify sampling in the ray tracing stage. Increasing the value increases the deviation from the ground truth but reduces the noise\n"
"    float GGXImportanceSampleBias            DEFAULT_VALUE(0.3f);\n"
"\n"
"    // The value controls the kernel size in the spatial reconstruction step. Increasing the value increases the deviation from the ground truth but reduces the noise\n"
"    float SpatialReconstructionRadius        DEFAULT_VALUE(4.0f);\n"
"\n"
"    // A factor to control the accmulation of history values of radiance buffer. Higher values reduce noise, but are more likely to exhibit ghosting artefacts\n"
"    float TemporalRadianceStabilityFactor    DEFAULT_VALUE(1.0f);\n"
"\n"
"    // A factor to control the accmulation of history values of variance buffer. Higher values reduce noise, but are more likely to exhibit ghosting artefacts\n"
"    float TemporalVarianceStabilityFactor    DEFAULT_VALUE(0.9f);\n"
"\n"
"    // This parameter represents the standard deviation in the Gaussian kernel, which forms the spatial component of the bilateral filter\n"
"    float BilateralCleanupSpatialSigmaFactor DEFAULT_VALUE(0.9f);\n"
"};\n"
"\n"
"#ifdef CHECK_STRUCT_ALIGNMENT\n"
"    CHECK_STRUCT_ALIGNMENT(ScreenSpaceReflectionAttribs);\n"
"#endif\n"
"\n"
"#endif //_SCREEN_SPACE_REFLECTION_STRUCTURES_FXH_\n"
