"#ifndef _TEMPORAL_ANTI_ALIASING_STRUCTURES_FXH_\n"
"#define _TEMPORAL_ANTI_ALIASING_STRUCTURES_FXH_\n"
"\n"
"#ifndef __cplusplus\n"
"#   include \"ShaderDefinitions.fxh\"\n"
"#elif !defined(_SHADER_DEFINITIONS_FXH_)\n"
"#   error \"Include ShaderDefinitions.fxh before including this file\"\n"
"#endif\n"
"\n"
"\n"
"// This parameter sets the minimum value for the variance gamma.\n"
"// The variance gamma is used to adjust the influence of historical data in the anti-aliasing process.\n"
"// A lower value means that the algorithm is less influenced by past frames, making it more responsive to changes but potentially less smooth\n"
"#define TAA_MIN_VARIANCE_GAMMA           0.75\n"
"\n"
"// This parameter sets the maximum value for the variance gamma.\n"
"// A higher maximum value allows the algorithm to rely more heavily on historical data,\n"
"// which can produce smoother results but may also introduce more motion blur or ghosting effects in fast-moving scenes.\n"
"#define TAA_MAX_VARIANCE_GAMMA           2.5\n"
"\n"
"// This parameter defines the threshold for pixel velocity difference that determines whether a pixel is considered to have \"no history.\"\n"
"// If the difference in motion vectors between the current frame and the previous frame exceeds this value, the pixel is treated as if it has no historical data.\n"
"// This helps to prevent ghosting effects by not blending pixels with significantly different motion vectors.\n"
"#define TAA_MOTION_VECTOR_DIFF_FACTOR  256.0\n"
"\n"
"// This parameter sets the threshold for depth disocclusion. It is used to determine how much a change in depth between frames should be considered as disocclusion,\n"
"// which occurs when previously occluded objects become visible. A small threshold value means that only significant depth changes will be treated as disocclusion,\n"
"// which can help in maintaining the stability of the image but may ignore some smaller, yet visually important changes.\n"
"#define TAA_DEPTH_DISOCCLUSION_THRESHOLD 0.9\n"
"\n"
"// This parameter sets the max \"distance\" between source colour and target colour.\n"
"// Setting this to a larger value allows more bright pixels from the history buffer to be leaved unchanged.\n"
"#define TAA_VARIANCE_INTERSECTION_MAX_T  10.0\n"
"\n"
"struct TemporalAntiAliasingAttribs\n"
"{\n"
"    // The value is responsible for interpolating between the current and previous frame. Increasing the value increases temporal stability but may introduce ghosting\n"
"    float TemporalStabilityFactor    DEFAULT_VALUE(0.9375f);\n"
"\n"
"    // If this parameter is set to true, the current frame will be written to the current history buffer without interpolation with the previous history buffer\n"
"    BOOL  ResetAccumulation          DEFAULT_VALUE(FALSE);\n"
"\n"
"    BOOL  SkipRejection              DEFAULT_VALUE(FALSE);\n"
"\n"
"    float Padding1                   DEFAULT_VALUE(0.0);\n"
"};\n"
"\n"
"#endif //_TEMPORAL_ANTI_ALIASING_STRUCTURES_FXH_\n"
