"#ifndef _TONE_MAPPING_STRUCTURES_FXH_\n"
"#define _TONE_MAPPING_STRUCTURES_FXH_\n"
"\n"
"#ifndef __cplusplus\n"
"#   include \"ShaderDefinitions.fxh\"\n"
"#elif !defined(_SHADER_DEFINITIONS_FXH_)\n"
"#   error \"Include ShaderDefinitions.fxh before including this file\"\n"
"#endif\n"
"\n"
"// Tone mapping mode\n"
"#define TONE_MAPPING_MODE_NONE          0\n"
"#define TONE_MAPPING_MODE_EXP           1\n"
"#define TONE_MAPPING_MODE_REINHARD      2\n"
"#define TONE_MAPPING_MODE_REINHARD_MOD  3\n"
"#define TONE_MAPPING_MODE_UNCHARTED2    4\n"
"#define TONE_MAPPING_FILMIC_ALU         5\n"
"#define TONE_MAPPING_LOGARITHMIC        6\n"
"#define TONE_MAPPING_ADAPTIVE_LOG       7\n"
"#define TONE_MAPPING_AGX                8\n"
"#define TONE_MAPPING_AGX_PUNCHY         9\n"
"\n"
"struct ToneMappingAttribs\n"
"{\n"
"    // Tone mapping mode.\n"
"    int   iToneMappingMode                  DEFAULT_VALUE(TONE_MAPPING_MODE_UNCHARTED2);\n"
"    // Automatically compute exposure to use in tone mapping.\n"
"    BOOL  bAutoExposure                     DEFAULT_VALUE(TRUE);\n"
"    // Middle gray value used by tone mapping operators.\n"
"    float fMiddleGray                       DEFAULT_VALUE(0.18f);\n"
"    // Simulate eye adaptation to light changes.\n"
"    BOOL  bLightAdaptation                  DEFAULT_VALUE(TRUE);\n"
"\n"
"    // White point to use in tone mapping.\n"
"    float fWhitePoint                       DEFAULT_VALUE(3.f);\n"
"    // Luminance point to use in tone mapping.\n"
"    float fLuminanceSaturation              DEFAULT_VALUE(1.f);\n"
"    uint Padding0                           DEFAULT_VALUE(0);\n"
"    uint Padding1                           DEFAULT_VALUE(0);\n"
"};\n"
"#ifdef CHECK_STRUCT_ALIGNMENT\n"
"    CHECK_STRUCT_ALIGNMENT(ToneMappingAttribs);\n"
"#endif\n"
"\n"
"#endif // _TONE_MAPPING_STRUCTURES_FXH_\n"
